Welcome to your new dbt project!

### Using the starter project

Try running the following commands:
- dbt run
- dbt test


### Resources:
- Learn more about dbt [in the docs](https://docs.getdbt.com/docs/introduction)
- Check out [Discourse](https://discourse.getdbt.com/) for commonly asked questions and answers
- Join the [chat](https://community.getdbt.com/) on Slack for live discussions and support
- Find [dbt events](https://events.getdbt.com) near you
- Check out [the blog](https://blog.getdbt.com/) for the latest news on dbt's development and best practices
# dbt_showcase

```bash
make setup
poetry shell
```

## DuckDB

```bash
# install duckdb
make setup-duckdb
# populate seeds to db
dbt seed --profile duckdb
# run dbt models
dbt run --profile duckdb --select youtube
 ```

## Athena

#### Prerequisites
- Create an s3 bucket to store data / query results for Athena `athena-dbt-showcase-trpijfd`
- Go to Athena > Workgroups > create a workgroup primary if it does not exist and set output location to 
`s3://athena-dbt-showcase-trpijfd/athena/query-results/`
- Go to Athena > Query Editor > settings > output location `s3://athena-dbt-showcase-trpijfd/athena/query-results/`
- Go to Athena > Query Editor
    ```sql
    CREATE DATABASE IF NOT EXISTS datahub
    COMMENT 'Analytics models generated by dbt (development)'
    LOCATION 's3://athena-dbt-showcase-trpijfd/athena/query-results/'
    WITH DBPROPERTIES ('creator'='Vincent Claes', 'email'='vclaes1986@gmail.com')
    ```
- Update the [profiles.yml](./profiles.yml)

```bash
# configure credentials for default profile
aws configure

# Change the date to "ingestion_date" of the seeds.
# Date is a reserved keyword in presto.
# You could use backticks around `date` in the command that
# executes the creation of the tables 
# but apparently the athena plugin does not do this :-/
# to see the commands Athena > Recent queries

dbt seed --profile athena
# check the files on s3
# https://s3.console.aws.amazon.com/s3/buckets/dbt-showcase?region=eu-west-1&prefix=athena/&showversions=false

# run dbt models
dbt run --profile athena --select youtube

(dbt-duckdb-showcase-py3.10) @vincentclaes ➜ /workspaces/dbt_showcase (athena ✗) $ dbt run --profile athena --select youtube
09:20:06  Running with dbt=1.3.0
09:20:06  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.dbt_showcase.example

09:20:06  Found 4 models, 0 tests, 0 snapshots, 0 analyses, 275 macros, 0 operations, 2 seed files, 0 sources, 0 exposures, 0 metrics
09:20:06  
09:20:09  Concurrency: 1 threads (target='dev')
09:20:09  
09:20:09  1 of 4 START sql view model datahub.join ....................................... [RUN]
Failed to execute query.
Traceback (most recent call last):
  File "/home/vscode/.cache/pypoetry/virtualenvs/dbt-duckdb-showcase-oyWVMt5I-py3.10/lib/python3.10/site-packages/pyathena/common.py", line 494, in _execute
    query_id = retry_api_call(
  File "/home/vscode/.cache/pypoetry/virtualenvs/dbt-duckdb-showcase-oyWVMt5I-py3.10/lib/python3.10/site-packages/pyathena/util.py", line 84, in retry_api_call
    return retry(func, *args, **kwargs)
  File "/home/vscode/.cache/pypoetry/virtualenvs/dbt-duckdb-showcase-oyWVMt5I-py3.10/lib/python3.10/site-packages/tenacity/__init__.py", line 406, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/vscode/.cache/pypoetry/virtualenvs/dbt-duckdb-showcase-oyWVMt5I-py3.10/lib/python3.10/site-packages/tenacity/__init__.py", line 351, in iter
    return fut.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/vscode/.cache/pypoetry/virtualenvs/dbt-duckdb-showcase-oyWVMt5I-py3.10/lib/python3.10/site-packages/tenacity/__init__.py", line 409, in __call__
    result = fn(*args, **kwargs)
  File "/home/vscode/.cache/pypoetry/virtualenvs/dbt-duckdb-showcase-oyWVMt5I-py3.10/lib/python3.10/site-packages/botocore/client.py", line 515, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/vscode/.cache/pypoetry/virtualenvs/dbt-duckdb-showcase-oyWVMt5I-py3.10/lib/python3.10/site-packages/botocore/client.py", line 934, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: Queries of this type are not supported

 ```

